/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class Administrador extends javax.swing.JFrame {

    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
        initComponents2();
        this.setTitle("Biblioteca 2022"); 
    }
        private void initComponents2(){
            setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CrearUsu = new javax.swing.JButton();
        EliminarUsu = new javax.swing.JButton();
        ReporteBibli = new javax.swing.JButton();
        ModificarUsu = new javax.swing.JButton();
        ModificarBibli = new javax.swing.JButton();
        EliminarBibli = new javax.swing.JButton();
        MostrarBibli = new javax.swing.JButton();
        CrearBibli = new javax.swing.JButton();
        ReporteUsu = new javax.swing.JButton();
        MostrarBibli1 = new javax.swing.JButton();
        MostrarBibli2 = new javax.swing.JButton();
        MostrarUsu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CrearUsu.setText("Crear");
        CrearUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearUsuMouseClicked(evt);
            }
        });
        CrearUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearUsuActionPerformed(evt);
            }
        });
        jPanel1.add(CrearUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 70, 30));

        EliminarUsu.setText("Eliminar");
        EliminarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUsuActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 70, 30));

        ReporteBibli.setText("Reporte Libros");
        ReporteBibli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteBibliActionPerformed(evt);
            }
        });
        jPanel1.add(ReporteBibli, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 630, 120, 30));

        ModificarUsu.setText("Modificar");
        ModificarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarUsuActionPerformed(evt);
            }
        });
        jPanel1.add(ModificarUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 70, 30));

        ModificarBibli.setText("Modificar");
        ModificarBibli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarBibliActionPerformed(evt);
            }
        });
        jPanel1.add(ModificarBibli, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 70, 30));

        EliminarBibli.setText("Eliminar");
        EliminarBibli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarBibliActionPerformed(evt);
            }
        });
        jPanel1.add(EliminarBibli, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 490, 70, 30));

        MostrarBibli.setText("Regresar");
        MostrarBibli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarBibliActionPerformed(evt);
            }
        });
        jPanel1.add(MostrarBibli, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 630, 100, 40));

        CrearBibli.setText("Crear");
        CrearBibli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearBibliActionPerformed(evt);
            }
        });
        jPanel1.add(CrearBibli, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 490, 70, 30));

        ReporteUsu.setText("Reporte Usuario");
        ReporteUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReporteUsuActionPerformed(evt);
            }
        });
        jPanel1.add(ReporteUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 630, 120, 30));

        MostrarBibli1.setText("Mostrar");
        MostrarBibli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarBibli1ActionPerformed(evt);
            }
        });
        jPanel1.add(MostrarBibli1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 70, 30));

        MostrarBibli2.setText("Salir");
        MostrarBibli2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarBibli2ActionPerformed(evt);
            }
        });
        jPanel1.add(MostrarBibli2, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 630, 100, 40));

        MostrarUsu.setText("Mostrar");
        MostrarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostrarUsuActionPerformed(evt);
            }
        });
        jPanel1.add(MostrarUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 70, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhatsApp Image 2022-02-28 at 8.25.42 PM.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReporteBibliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteBibliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReporteBibliActionPerformed

    private void MostrarBibliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarBibliActionPerformed
            Login prin = new Login ();
            prin.setVisible(true);
            dispose();
    }//GEN-LAST:event_MostrarBibliActionPerformed

    private void CrearUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearUsuActionPerformed
            principal prin = new principal ();
            prin.setVisible(true);
            dispose();
    }//GEN-LAST:event_CrearUsuActionPerformed

    private void CrearUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearUsuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearUsuMouseClicked

    private void MostrarBibli2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarBibli2ActionPerformed
            LoginUsuariosAdmin prin = new LoginUsuariosAdmin ();
            prin.setVisible(true);
            dispose();
    }//GEN-LAST:event_MostrarBibli2ActionPerformed

    private void MostrarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarUsuActionPerformed
            principal prin = new principal ();
            prin.setVisible(true);
            dispose();
    }//GEN-LAST:event_MostrarUsuActionPerformed

    private void CrearBibliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearBibliActionPerformed
            CrearBibliografica prin = new CrearBibliografica ();
            prin.setVisible(true);
            dispose();
    }//GEN-LAST:event_CrearBibliActionPerformed

    private void ReporteUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReporteUsuActionPerformed
        
    }//GEN-LAST:event_ReporteUsuActionPerformed

    private void ModificarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarUsuActionPerformed
            principal prin = new principal ();
            prin.setVisible(true);
            dispose();
    }//GEN-LAST:event_ModificarUsuActionPerformed

    private void EliminarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUsuActionPerformed
            principal prin = new principal ();
            prin.setVisible(true);
            dispose();
    }//GEN-LAST:event_EliminarUsuActionPerformed

    private void ModificarBibliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarBibliActionPerformed
            CrearBibliografica prin = new CrearBibliografica ();
            prin.setVisible(true);
            dispose();
    }//GEN-LAST:event_ModificarBibliActionPerformed

    private void EliminarBibliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarBibliActionPerformed
            CrearBibliografica prin = new CrearBibliografica ();
            prin.setVisible(true);
            dispose();
    }//GEN-LAST:event_EliminarBibliActionPerformed

    private void MostrarBibli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarBibli1ActionPerformed
            CrearBibliografica prin = new CrearBibliografica ();
            prin.setVisible(true);
            dispose();
    }//GEN-LAST:event_MostrarBibli1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CrearBibli;
    private javax.swing.JButton CrearUsu;
    private javax.swing.JButton EliminarBibli;
    private javax.swing.JButton EliminarUsu;
    private javax.swing.JButton ModificarBibli;
    private javax.swing.JButton ModificarUsu;
    private javax.swing.JButton MostrarBibli;
    private javax.swing.JButton MostrarBibli1;
    private javax.swing.JButton MostrarBibli2;
    private javax.swing.JButton MostrarUsu;
    private javax.swing.JButton ReporteBibli;
    private javax.swing.JButton ReporteUsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
