
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class CrearBibliografica extends javax.swing.JFrame {

    /**
     * @return the listaLibros
     */
    public static Libros[] getListaLibros() {
        return listaLibros;
    }

    /**
     * @param aListaLibros the listaLibros to set
     */
    public static void setListaLibros(Libros[] aListaLibros) {
        listaLibros = aListaLibros;
    }
    private static  Libros[] listaLibros = new Libros[2];
    
    static DefaultTableModel dtm=new DefaultTableModel ();
    
    DefaultTableModel modelo;
    
    
        

    /**
     * Creates new form CrearBibliografica
     */
    public CrearBibliografica() {
        
        
        initComponents();
        initComponents2();
        this.setTitle("Biblioteca 2022");
        String[] titulo=new String[]{"Autor:", "Fecha", "Titulo","Descripcion","Palabras","Edicion","Temas","Copias","Area","Categoria","ISBN"};
        dtm.setColumnIdentifiers (titulo);
        tblDatos.setModel (dtm);
        
    }
        public void initComponents2(){
            setLocationRelativeTo(null);
    }
    void agregar (){
        dtm.addRow(new Object[]{
        Autor.getText(),Fecha.getText(),Titulo.getText(),Descripcion.getText(),Palabras.getText(),Edicion.getText(),Temas.getText(),Copias.getText(),Area.getText(),Categoria.getText(),isbn.getText()
            });
        }
    void eliminar () {
        int fila=tblDatos.getSelectedRow ();
        dtm.removeRow (fila);
        }
        void actualizar () {
        int fila=tblDatos.getSelectedRow ();
        dtm.setValueAt (Autor. getText (), fila, 0);
        dtm.setValueAt (Fecha.getText (), fila, 1);
        dtm.setValueAt (Titulo.getText (), fila, 2);
        dtm.setValueAt (Descripcion. getText (), fila, 3);
        dtm.setValueAt (Palabras. getText (), fila, 4);
        dtm.setValueAt (Edicion. getText (), fila, 5);
        dtm.setValueAt (Temas. getText (), fila, 6);
        dtm.setValueAt (Copias. getText (), fila, 7);
        dtm.setValueAt (Area. getText (), fila, 8);
        dtm.setValueAt (Categoria. getText (), fila, 9);
        dtm.setValueAt (isbn. getText (), fila, 10);
        }
        void limpiarTabla () {
        int filas=dtm.getRowCount ();
        for (int i=0;i<filas;i++) {
        dtm.removeRow (0);
        
        }
        }
        
       
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Autor = new javax.swing.JTextField();
        Fecha = new javax.swing.JTextField();
        Titulo = new javax.swing.JTextField();
        Descripcion = new javax.swing.JTextField();
        Palabras = new javax.swing.JTextField();
        Edicion = new javax.swing.JTextField();
        Temas = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        RegresarLibro = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        Copias = new javax.swing.JTextField();
        Area = new javax.swing.JTextField();
        Categoria = new javax.swing.JTextField();
        isbn = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(Autor, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 80, 160, 30));
        jPanel1.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 160, 30));

        Titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TituloActionPerformed(evt);
            }
        });
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 160, 30));
        jPanel1.add(Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 160, 30));
        jPanel1.add(Palabras, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 160, 30));

        Edicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdicionActionPerformed(evt);
            }
        });
        jPanel1.add(Edicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 160, 30));
        jPanel1.add(Temas, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 160, 30));

        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel1.add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 660, 110, 30));

        RegresarLibro.setText("Regresar");
        RegresarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarLibroActionPerformed(evt);
            }
        });
        jPanel1.add(RegresarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 660, 110, 30));

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        jPanel1.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 660, 110, 30));

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 660, 110, 30));

        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(Limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 660, 100, 30));

        Copias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopiasActionPerformed(evt);
            }
        });
        jPanel1.add(Copias, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 390, 160, 30));
        jPanel1.add(Area, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 160, 30));

        Categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CategoriaActionPerformed(evt);
            }
        });
        jPanel1.add(Categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 160, 30));
        jPanel1.add(isbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 160, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libro", "Revista", "Tesis", "Libro digital", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 570, 140, 30));

        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblDatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 1110, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhatsApp.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EdicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdicionActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
       agregar ();
    }//GEN-LAST:event_guardarActionPerformed

    private void RegresarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarLibroActionPerformed
            Administrador prin = new Administrador ();
            prin.setVisible(true);
            dispose();
    }//GEN-LAST:event_RegresarLibroActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
            actualizar ();
    }//GEN-LAST:event_modificarActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
            eliminar ();
    }//GEN-LAST:event_EliminarActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
        Autor.setText("");
        Fecha.setText("");
        Titulo.setText("");
        Descripcion.setText("");
        Palabras.setText("");
        Edicion.setText("");
        Temas.setText("");
        Copias.setText("");
        Area.setText("");
        Categoria.setText("");
        isbn.setText("");
    }//GEN-LAST:event_LimpiarActionPerformed

    private void TituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TituloActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void CategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CategoriaActionPerformed

    private void CopiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CopiasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearBibliografica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearBibliografica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearBibliografica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearBibliografica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearBibliografica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Area;
    private javax.swing.JTextField Autor;
    private javax.swing.JTextField Categoria;
    private javax.swing.JTextField Copias;
    private javax.swing.JTextField Descripcion;
    private javax.swing.JTextField Edicion;
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField Fecha;
    private javax.swing.JButton Limpiar;
    private javax.swing.JTextField Palabras;
    private javax.swing.JButton RegresarLibro;
    private javax.swing.JTextField Temas;
    private javax.swing.JTextField Titulo;
    private javax.swing.JButton guardar;
    private javax.swing.JTextField isbn;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificar;
    private javax.swing.JTable tblDatos;
    // End of variables declaration//GEN-END:variables
}
