
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        initComponents2();
        this.setTitle("Biblioteca 2022"); 
    }
            private void initComponents2(){
            setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TContra = new javax.swing.JLabel();
        TUsu = new javax.swing.JLabel();
        Admi = new javax.swing.JTextField();
        AdminClave = new javax.swing.JPasswordField();
        Salir = new javax.swing.JButton();
        EntrarUsu = new javax.swing.JButton();
        RegresarAdmin1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TContra.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TContra.setForeground(new java.awt.Color(0, 0, 0));
        TContra.setText("Contraseña");
        jPanel1.add(TContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 170, 30));

        TUsu.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TUsu.setForeground(new java.awt.Color(0, 0, 0));
        TUsu.setText("Administrador");
        jPanel1.add(TUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 170, 30));

        Admi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdmiActionPerformed(evt);
            }
        });
        jPanel1.add(Admi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 360, -1));
        jPanel1.add(AdminClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 360, -1));

        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, 90, 40));

        EntrarUsu.setText("Entrar");
        EntrarUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EntrarUsuMouseClicked(evt);
            }
        });
        EntrarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarUsuActionPerformed(evt);
            }
        });
        jPanel1.add(EntrarUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 90, 40));

        RegresarAdmin1.setText("Regresar");
        RegresarAdmin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarAdmin1ActionPerformed(evt);
            }
        });
        jPanel1.add(RegresarAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 620, 270, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhatsApp Image 2022-02-23 at 5.01.30 PM.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdmiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AdmiActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_SalirActionPerformed

    private void EntrarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarUsuActionPerformed
        String usuario = "admin";
        String password = "admin";
        if (Admi.getText().equals(usuario)&&AdminClave.getText().equals(password)){
            Administrador prin = new Administrador ();
            prin.setVisible(true);
            dispose();
        }
        else{
            JOptionPane.showMessageDialog(this, "Usuario y Contraseña no coinciden por favor revise sus datos");  
        }     
        
    }//GEN-LAST:event_EntrarUsuActionPerformed

    private void EntrarUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarUsuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EntrarUsuMouseClicked

    private void RegresarAdmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarAdmin1ActionPerformed
        LoginUsuariosAdmin prin = new LoginUsuariosAdmin ();
        prin.setVisible(true);
        dispose();
    }//GEN-LAST:event_RegresarAdmin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Admi;
    private javax.swing.JPasswordField AdminClave;
    private javax.swing.JButton EntrarUsu;
    private javax.swing.JButton RegresarAdmin1;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel TContra;
    private javax.swing.JLabel TUsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
