
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class LoginUsuario extends javax.swing.JFrame {
    principal f2 = new principal();

    /**
     * Creates new form LoginUsuario
     */
    public LoginUsuario() {
        initComponents();
        initComponents2();
        this.setTitle("Biblioteca 2022"); 
        }
        private void initComponents2(){
        setLocationRelativeTo(null);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        UsuAdmin = new javax.swing.JTextField();
        ClaveAdmin = new javax.swing.JPasswordField();
        EntrarUsu = new javax.swing.JButton();
        SalirAdmin = new javax.swing.JButton();
        TUsu = new javax.swing.JLabel();
        TContra = new javax.swing.JLabel();
        RegresarAdmin1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsuAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsuAdminActionPerformed(evt);
            }
        });
        jPanel1.add(UsuAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 360, -1));
        jPanel1.add(ClaveAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, 360, -1));

        EntrarUsu.setText("Entrar");
        EntrarUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EntrarUsuMouseClicked(evt);
            }
        });
        EntrarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntrarUsuActionPerformed(evt);
            }
        });
        jPanel1.add(EntrarUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 460, 90, 40));

        SalirAdmin.setText("Salir");
        SalirAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirAdminActionPerformed(evt);
            }
        });
        jPanel1.add(SalirAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 460, 90, 40));

        TUsu.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TUsu.setForeground(new java.awt.Color(0, 0, 0));
        TUsu.setText("Usuario");
        jPanel1.add(TUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 170, 30));

        TContra.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TContra.setForeground(new java.awt.Color(0, 0, 0));
        TContra.setText("Contraseña");
        jPanel1.add(TContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 170, 30));

        RegresarAdmin1.setText("Regresar");
        RegresarAdmin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarAdmin1ActionPerformed(evt);
            }
        });
        jPanel1.add(RegresarAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 620, 270, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/WhatsApp Image 2022-02-23 at 5.01.30 PM.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 700));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsuAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsuAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsuAdminActionPerformed

    private void EntrarUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntrarUsuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EntrarUsuMouseClicked

    private void EntrarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntrarUsuActionPerformed
        
        Boolean existeusuario = false;
        for (int i = 0; i < f2.getListaUsuario().length; i++) {
            if (f2.getListaUsuario()[i] != null){
                if (f2.getListaUsuario()[i].getUser().equals(UsuAdmin.getText()) 
                        && f2.getListaUsuario()[i].getClave().equals(ClaveAdmin.getText())){
                    
                    existeusuario = true;
                }
                else{
                JOptionPane.showMessageDialog(this, "Usuario y Contraseña no coinciden por favor revise sus datos");  
                } 
                break;
            }   
        }
        if(existeusuario) {
            PlataformaUsuario prin = new PlataformaUsuario ();
            prin.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(null, "El Usuario no existe, ponerse en contacto con el administrador para solicitar un registro :D");
        }
                
    }//GEN-LAST:event_EntrarUsuActionPerformed

    private void SalirAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirAdminActionPerformed
        System.exit(0);

    }//GEN-LAST:event_SalirAdminActionPerformed

    private void RegresarAdmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarAdmin1ActionPerformed
            LoginUsuariosAdmin prin = new LoginUsuariosAdmin ();
            prin.setVisible(true);
            dispose();
    }//GEN-LAST:event_RegresarAdmin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ClaveAdmin;
    private javax.swing.JButton EntrarUsu;
    private javax.swing.JButton RegresarAdmin1;
    private javax.swing.JButton SalirAdmin;
    private javax.swing.JLabel TContra;
    private javax.swing.JLabel TUsu;
    private javax.swing.JTextField UsuAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private static class JOpcionPanel {

        private static void showMessageDialog(LoginUsuario aThis, String usuario_y_Contraseña_no_coinciden_por_fav) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public JOpcionPanel() {
        }
    }
}
