
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class PrestamoDeLibro extends javax.swing.JFrame {
    static DefaultTableModel dtm=new DefaultTableModel ();

    /**
     * Creates new form BibliotecaVirtual
     */
    
    static public  DefaultTableModel modelo2;

    /**
     * Creates new form PrestamoDeLibro
     */
    public PrestamoDeLibro() {
        initComponents();
        initComponents2();
        String[] titulo=new String[]{"No", "Titulo", "Autor","Agregar"};
        dtm.setColumnIdentifiers (titulo);
        TablaDatos.setModel (dtm);
    } 
        private void initComponents2(){
        this.setTitle("Biblioteca 2022");
        setLocationRelativeTo(null);
        }
        void agregar (){
        dtm.addRow(new Object[]{
        L1.getText(),L2.getText(),L3.getText()});}
        void agregar2 (){
        dtm.addRow(new Object[]{
        R1.getText(),R2.getText(),R3.getText()});}
        void agregar3 (){
        dtm.addRow(new Object[]{
        T1.getText(),T2.getText(),T3.getText()});}
            
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RegresarPre = new javax.swing.JButton();
        LogoutPres = new javax.swing.JButton();
        VerPrestamo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        L1 = new javax.swing.JTextField();
        L2 = new javax.swing.JTextField();
        L3 = new javax.swing.JTextField();
        R1 = new javax.swing.JTextField();
        R2 = new javax.swing.JTextField();
        R3 = new javax.swing.JTextField();
        T1 = new javax.swing.JTextField();
        T2 = new javax.swing.JTextField();
        T3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegresarPre.setText("Regresar");
        RegresarPre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarPreActionPerformed(evt);
            }
        });
        jPanel1.add(RegresarPre, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 210, 110, 40));

        LogoutPres.setText("Logout");
        LogoutPres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutPresActionPerformed(evt);
            }
        });
        jPanel1.add(LogoutPres, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 130, 110, 40));

        VerPrestamo.setText("Ver Prestamo");
        VerPrestamo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerPrestamoActionPerformed(evt);
            }
        });
        jPanel1.add(VerPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 180, 30));

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaDatos);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, 500, 90));

        jButton1.setText("Ver Libros");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 630, 210, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Prestamo.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        L1.setText("1");
        jPanel1.add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        L2.setText("Don Quijote de la Mancha​");
        jPanel1.add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        L3.setText("Miguel de Cervantes");
        jPanel1.add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, -1, -1));

        R1.setText("2");
        R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1ActionPerformed(evt);
            }
        });
        jPanel1.add(R1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, -1));

        R2.setText("Peopel");
        jPanel1.add(R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, -1, -1));

        R3.setText("XXXXXX");
        jPanel1.add(R3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, -1, -1));

        T1.setText("3");
        jPanel1.add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        T2.setText("La Ingenieria en Tiempos actuales");
        jPanel1.add(T2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 140, 20));

        T3.setText("Christian Marroquin");
        jPanel1.add(T3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarPreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarPreActionPerformed
            PlataformaUsuario prin = new PlataformaUsuario ();
            prin.setVisible(true);
            dispose();
    }//GEN-LAST:event_RegresarPreActionPerformed

    private void LogoutPresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutPresActionPerformed
       LoginUsuario prin = new LoginUsuario ();
        prin.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutPresActionPerformed

    private void VerPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerPrestamoActionPerformed
        Prestamo prin = new Prestamo ();
        prin.setVisible(true);
        dispose();
    }//GEN-LAST:event_VerPrestamoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            agregar ();
            agregar2 ();
            agregar3 ();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrestamoDeLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrestamoDeLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrestamoDeLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrestamoDeLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrestamoDeLibro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField L1;
    private javax.swing.JTextField L2;
    private javax.swing.JTextField L3;
    private javax.swing.JButton LogoutPres;
    private javax.swing.JTextField R1;
    private javax.swing.JTextField R2;
    private javax.swing.JTextField R3;
    private javax.swing.JButton RegresarPre;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTable TablaDatos;
    private javax.swing.JButton VerPrestamo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
