

import javax.swing.table.DefaultTableModel;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class Prestamo extends javax.swing.JFrame {
    static DefaultTableModel dtm=new DefaultTableModel ();

    /**
     * Creates new form Prestamo
     */
    public Prestamo() {
        initComponents();
        initComponents2();
        String[] titulo=new String[]{"No", "Titulo", "Autor","Agregar"};
        dtm.setColumnIdentifiers (titulo);
        TablaDatos.setModel (dtm);
        
    } 
        private void initComponents2(){
        this.setTitle("Biblioteca 2022");
            setLocationRelativeTo(null);
            
     }
        void agregar (){
        dtm.addRow(new Object[]{
        L1.getText(),L2.getText(),L3.getText()});}
        void agregar2 (){
        dtm.addRow(new Object[]{
        R1.getText(),R2.getText(),R3.getText()});}
        void agregar3 (){
        dtm.addRow(new Object[]{
        T1.getText(),T2.getText(),T3.getText()});}
        
        void eliminar () {
        int fila=TablaDatos.getSelectedRow ();
        dtm.removeRow (fila);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        RegresarLis = new javax.swing.JButton();
        LogoutLis = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        Quijote = new javax.swing.JButton();
        People = new javax.swing.JButton();
        Tesis = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        L1 = new javax.swing.JTextField();
        L2 = new javax.swing.JTextField();
        L3 = new javax.swing.JTextField();
        R1 = new javax.swing.JTextField();
        R2 = new javax.swing.JTextField();
        R3 = new javax.swing.JTextField();
        T1 = new javax.swing.JTextField();
        T2 = new javax.swing.JTextField();
        T3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        RegresarLis.setText("Regresar");
        RegresarLis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarLisActionPerformed(evt);
            }
        });
        jPanel1.add(RegresarLis, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 210, 110, 40));

        LogoutLis.setText("Logout");
        LogoutLis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutLisActionPerformed(evt);
            }
        });
        jPanel1.add(LogoutLis, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 130, 110, 40));

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Autor", "Años", "Agregar"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(TablaDatos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 680, 190));

        Quijote.setText("Quijote de La Mancha");
        Quijote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuijoteActionPerformed(evt);
            }
        });
        jPanel1.add(Quijote, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, 150, 30));

        People.setText("People");
        People.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PeopleActionPerformed(evt);
            }
        });
        jPanel1.add(People, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 390, 150, 30));

        Tesis.setText("Tesis");
        Tesis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TesisActionPerformed(evt);
            }
        });
        jPanel1.add(Tesis, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 430, 150, 30));

        Eliminar.setText("Regresar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        jPanel1.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 470, 150, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presstamo.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1111, 700));

        L1.setText("1");
        jPanel1.add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        L2.setText("Don Quijote de la Mancha​");
        jPanel1.add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        L3.setText("Miguel de Cervantes");
        jPanel1.add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, -1, -1));

        R1.setText("2");
        R1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                R1ActionPerformed(evt);
            }
        });
        jPanel1.add(R1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, -1));

        R2.setText("Peopel");
        jPanel1.add(R2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, -1, -1));

        R3.setText("XXXXXX");
        jPanel1.add(R3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, -1, -1));

        T1.setText("3");
        jPanel1.add(T1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        T2.setText("La Ingenieria en Tiempos actuales");
        jPanel1.add(T2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 380, 140, 20));

        T3.setText("Christian Marroquin");
        jPanel1.add(T3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 380, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarLisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarLisActionPerformed
            PrestamoDeLibro prin = new PrestamoDeLibro ();
            prin.setVisible(true);
            dispose();
    }//GEN-LAST:event_RegresarLisActionPerformed

    private void LogoutLisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutLisActionPerformed
       LoginUsuario prin = new LoginUsuario ();
        prin.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutLisActionPerformed

    private void R1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_R1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_R1ActionPerformed

    private void QuijoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuijoteActionPerformed
        agregar ();
    }//GEN-LAST:event_QuijoteActionPerformed

    private void PeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PeopleActionPerformed
        agregar2 ();
    }//GEN-LAST:event_PeopleActionPerformed

    private void TesisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TesisActionPerformed
        agregar3 ();
    }//GEN-LAST:event_TesisActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
       eliminar ();
    }//GEN-LAST:event_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Eliminar;
    private javax.swing.JTextField L1;
    private javax.swing.JTextField L2;
    private javax.swing.JTextField L3;
    private javax.swing.JButton LogoutLis;
    private javax.swing.JButton People;
    private javax.swing.JButton Quijote;
    private javax.swing.JTextField R1;
    private javax.swing.JTextField R2;
    private javax.swing.JTextField R3;
    private javax.swing.JButton RegresarLis;
    private javax.swing.JTextField T1;
    private javax.swing.JTextField T2;
    private javax.swing.JTextField T3;
    private javax.swing.JTable TablaDatos;
    private javax.swing.JButton Tesis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
